apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
  namespace: demo
spec:
  selector:
    app: spring-boot-app
  ports:
  - name: http
    port: 8012
    targetPort: 8080
  type: LoadBalancer
