---
# tasks file for grafana_install
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install required utilities
      apt:
        name:
          - apt-transport-https
          - software-properties-common
        state: present

    - name: Import Grafana GPG key
      get_url:
        url: https://apt.grafana.com/gpg.key
        dest: /usr/share/keyrings/grafana.key

    - name: Add Grafana repository
      copy:
        content: "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main"
        dest: /etc/apt/sources.list.d/grafana.list

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Grafana
      apt:
        name: grafana
        state: present

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start Grafana service
      systemd:
        name: grafana-server
        enabled: yes
        state: started
