---
route:
  group_by:
    - alertname
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: email-notifications
receivers:
  - name: email-notifications
    email_configs:
      - to: badrivarun09@gmail.com #for example:- to: username@gmail.com
        from: test@example.com
        smarthost: smtp.gmail.com:587
        auth_username: badrivarun09@gmail.com #for example:- to: username@gmail.com
        auth_identity: badrivarun09@gmail.com #for example:- to: username@gmail.com
        auth_password: pxai ttwf nzcl lgxe # for example: xuwy plmh xdqv kirr
        send_resolved: true
inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal:
      - alertname
      - dev
      - instance

