---
route:
  group_by:
    - alertname
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: email-notifications
receivers:
  - name: email-notifications
    email_configs:
      - to: <username@gmail.com> #replace your gmail-id <username@gmail.com>
        from: test@example.com
        smarthost: smtp.gmail.com:587
        auth_username: <username@gmail.com> #replace your gmail-id <username@gmail.com>
        auth_identity: <username@gmail.com> #replace your gmail-id <username@gmail.com>
        auth_password: <gmail_APP_password> #for example: xuwy plmh xdqv kirr
        send_resolved: true
inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal:
      - alertname
      - dev
      - instance

